version: '2'
services:
  sonarr:
    image: linuxserver/sonarr
    restart: always
    ports:
    - "8989:8989"
    environment:
      - TZ=Europe/London
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/docker/sonarr:/config
      - /mnt/plex/tv:/tv


